_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
protect_all_forms: false
unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
log: true
element_name: your_email_address
time_limit: 5
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_feedback_form: true
  contact_message_personal_form: true
  node_event_form: false
  node_files_form: false
  node_news_form: false
  node_page_form: false
  node_parish_council_form: false
  node_quickevent_form: false
  node_webform_form: false
  comment_comment_form: true
